### ISSUE TITLE
Remove Domains

### ISSUE THREAD

**Issue by Cybo1927** [AmmoniteFilter/AmmoniteFilter#2]
I don't know why `pusher.com` is blocked, and there may be a legitimate reason but it's used by a service called GoGuardian which is what my school uses to monitor and control school Chromebooks. It's often queried right after GoGuardian which is how I figured out how to unbreak their service; it's a required connection.

![image](https://user-images.githubusercontent.com/39284087/114940402-50bbc080-9e31-11eb-8f15-0ebf64ae5ed1.png)

**Comment by Cybo1927** [comment]
Tripadvisor is blocked from CNAME, please remove `cs477.adn.etacdn.net`.

![image](https://user-images.githubusercontent.com/39284087/114950166-05f67480-9e42-11eb-80be-0c707a25bce7.png)

**Comment by ammnt** [comment]
@Cybo1927, thank you for your help. These domains will be removed in next update tomorrow🤘
